# frozen_string_literal: true

# generated by this command:
# rails g graphql:object article author:author

module Types
  class ArticleType < Types::BaseObject
    field :id, ID, null: false do
      description "This is the article's ID."
    end

    field :title, String, null: false do
      description "This is the article's title."
    end

    field :body, String, null: false do
      description "This is the article's content."
    end

    field :author_id, Integer, null: false do
      description "The ID of this article's author."
    end

    field :created_at, GraphQL::Types::ISO8601DateTime, null: false do
      description "The date/time that this article was created at."
    end

    field :updated_at, GraphQL::Types::ISO8601DateTime, null: false do
      description "The date/time that this article was last updated at."
    end

    field :author, Types::AuthorType, null: false do
      description "The article's author in object form."
    end
  end
end
