# frozen_string_literal: true

# generated by this command:
# rails g graphql:object author article:article

module Types
  class AuthorType < Types::BaseObject
    field :id, ID, null: false do
      description "This is the author's ID."
    end

    field :name, String, null: false do
      description "This is the author's name."
    end

    field :created_at, GraphQL::Types::ISO8601DateTime, null: false do
      description "The date/time that this author was created at."
    end

    field :updated_at, GraphQL::Types::ISO8601DateTime, null: false do
      description "The date/time that this author was last updated at."
    end

    field :articles, [ ArticleType ] do
      description "The author's articles."
    end
  end
end
